"""F2-T4 — unit tests for the PolygonLookup engine.

Most tests run against a tiny synthetic GeoPackage (two touching squares in
EPSG:3435) so they are fast, deterministic, and independent of the real data.
Query points are generated by inverting known planar (3435) points back to
WGS84 lon/lat, so the test exercises the reprojection in both directions and
does not depend on the sign conventions of the projection. A final test runs
against the shipped data/layers.gpkg.
"""
import json
import math
from pathlib import Path

import geopandas as gpd
import pytest
from pyproj import Transformer
from shapely.geometry import box

from app.config import AppConfig, ConfigError, LayerConfig, load_config
from app.lookup import (
    InvalidCoordinateError,
    PolygonLookup,
    UnknownLayerError,
)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
REAL_CONFIG = PROJECT_ROOT / "config.toml"
REAL_GPKG = PROJECT_ROOT / "data" / "layers.gpkg"

# Two squares in EPSG:3435 (ftUS) near the Illinois State Plane East range, with
# a thin overlap strip straddling x = CX. The overlap (200 ft wide) is what lets
# a point be genuinely covered by BOTH polygons — an exact shared edge can't be
# hit reliably because the WGS84 round-trip perturbs the point by ~1e-4 ft.
CX, CY = 1_100_000.0, 1_900_000.0
HALF = 2_000.0
OVERLAP = 100.0
_INV = Transformer.from_crs("EPSG:3435", "EPSG:4326", always_xy=True)


def _lonlat(x: float, y: float) -> tuple[float, float]:
    """A WGS84 lon/lat that reprojects to planar (x, y) in EPSG:3435."""
    lon, lat = _INV.transform(x, y)
    return lon, lat


def _build_squares(tmp_path, west_name="alpha", east_name="beta") -> PolygonLookup:
    """Two overlapping squares (west at tree index 0, east at index 1).

    Names are parameterizable so a test can make the attribute-sort winner
    differ from the STRtree's natural-first element.
    """
    west = box(CX - HALF, CY - HALF, CX + OVERLAP, CY + HALF)  # extends east past CX
    east = box(CX - OVERLAP, CY - HALF, CX + HALF, CY + HALF)  # extends west past CX
    frame = gpd.GeoDataFrame(
        {"name": [west_name, east_name], "code": ["W", "E"]},
        geometry=[west, east],
        crs="EPSG:3435",
    )
    gpkg = tmp_path / f"squares_{west_name}_{east_name}.gpkg"
    frame.to_file(gpkg, layer="squares", driver="GPKG")

    config = AppConfig(
        layers={
            "squares": LayerConfig(
                id="squares",
                name="Test Squares",
                path=gpkg,
                layer="squares",
                attributes=("name", "code"),
                source="synthetic test fixture",
            )
        }
    )
    return PolygonLookup(config)


@pytest.fixture
def squares_lookup(tmp_path) -> PolygonLookup:
    return _build_squares(tmp_path)


def test_point_inside_west_square(squares_lookup):
    lon, lat = _lonlat(CX - HALF / 2, CY)  # clearly inside alpha (west)
    match = squares_lookup.locate(lon, lat, "squares")
    assert match.found
    assert match.feature == {"name": "alpha", "code": "W"}


def test_point_inside_east_square(squares_lookup):
    lon, lat = _lonlat(CX + HALF / 2, CY)  # clearly inside beta (east)
    match = squares_lookup.locate(lon, lat, "squares")
    assert match.found
    assert match.feature == {"name": "beta", "code": "E"}


@pytest.mark.parametrize(
    "west_name,east_name",
    [
        ("aaa", "zzz"),  # west (tree index 0) sorts first
        ("zzz", "aaa"),  # east (tree index 1) sorts first
    ],
)
def test_overlap_returns_attribute_minimum(tmp_path, west_name, east_name):
    # A point in the overlap is covered by BOTH squares. The engine must return
    # the one whose first attribute ("name") sorts first — regardless of which
    # tree index STRtree returns first. Testing both name orderings gives the
    # assertion teeth: if the tie-break sort were removed, the engine would
    # always return the STRtree's natural-first element (west, index 0), so the
    # ("zzz","aaa") case — where the correct answer is east — would fail.
    lookup = _build_squares(tmp_path, west_name=west_name, east_name=east_name)
    lon, lat = _lonlat(CX, CY)
    match = lookup.locate(lon, lat, "squares")
    assert match.found
    assert match.feature["name"] == min(west_name, east_name)


def test_point_outside_all_polygons(squares_lookup):
    lon, lat = _lonlat(CX + 10 * HALF, CY)  # far east of both squares
    match = squares_lookup.locate(lon, lat, "squares")
    assert not match.found
    assert match.reason == "point_outside_all_polygons"
    assert match.feature is None


def test_unknown_layer_raises(squares_lookup):
    with pytest.raises(UnknownLayerError):
        squares_lookup.locate(-87.63, 41.88, "no_such_layer")


@pytest.mark.parametrize("lon,lat", [(-999.0, 41.0), (0.0, 91.0), (200.0, 0.0)])
def test_garbage_coordinates_raise(squares_lookup, lon, lat):
    with pytest.raises(InvalidCoordinateError):
        squares_lookup.locate(lon, lat, "squares")


def test_feature_count_and_layer_ids(squares_lookup):
    assert squares_lookup.layer_ids == ("squares",)
    assert squares_lookup.feature_count("squares") == 2


# ---- config loader (F2-T1) ----

def test_load_config_missing_file(tmp_path):
    with pytest.raises(ConfigError):
        load_config(tmp_path / "does_not_exist.toml")


def test_load_config_missing_gpkg(tmp_path):
    bad = tmp_path / "config.toml"
    bad.write_text(
        '[[layers]]\nid="x"\nname="X"\npath="nope.gpkg"\nlayer="x"\n'
        'attributes=["a"]\nsource="s"\n'
    )
    with pytest.raises(ConfigError):
        load_config(bad)


# ---- real shipped data ----

@pytest.mark.skipif(not REAL_GPKG.exists(), reason="data/layers.gpkg not built")
def test_real_data_known_addresses():
    lookup = PolygonLookup(load_config(REAL_CONFIG))

    # Chicago City Hall (121 N LaSalle) → Police District 1 (Central).
    city_hall = lookup.locate(-87.63192, 41.88354, "police_districts")
    assert city_hall.found
    assert city_hall.feature["dist_num"] == "1"

    # Evanston is in Cook County but outside Chicago: no police district, but it
    # IS a municipality — the SPEC §4 "point_outside_all_polygons" case.
    evanston_pd = lookup.locate(-87.68770, 42.04512, "police_districts")
    assert not evanston_pd.found
    assert evanston_pd.reason == "point_outside_all_polygons"

    evanston_muni = lookup.locate(-87.68770, 42.04512, "municipalities")
    assert evanston_muni.found
    assert evanston_muni.feature["muni_name"] == "Evanston"


@pytest.mark.skipif(not REAL_GPKG.exists(), reason="data/layers.gpkg not built")
def test_real_data_null_attribute_serializes_as_none():
    # The municipalities layer has features with a null muni_name. A point inside
    # such a polygon must return JSON-valid None, never a float NaN (which is not
    # valid JSON and would break the frontend or force a 500).
    frame = gpd.read_file(REAL_GPKG, layer="municipalities")
    null_rows = frame[frame["muni_name"].isna()]
    if null_rows.empty:
        pytest.skip("no null muni_name in current data")

    inside = null_rows.geometry.iloc[0].representative_point()  # guaranteed inside
    to_wgs84 = Transformer.from_crs(frame.crs, "EPSG:4326", always_xy=True)
    lon, lat = to_wgs84.transform(inside.x, inside.y)

    lookup = PolygonLookup(load_config(REAL_CONFIG))
    match = lookup.locate(lon, lat, "municipalities")
    assert match.found
    value = match.feature["muni_name"]
    assert not (isinstance(value, float) and math.isnan(value)), "returned NaN"
    json.dumps(match.feature)  # must not raise
