"""F7-T3 — tests for the batch engine.

Everything runs against a tiny synthetic GeoPackage (two squares in EPSG:3435,
the same idiom as tests/test_lookup.py) and a stub geocoder object. There is no
network here at all: the lat/lon path never has one, and the address path is
served by a stub whose behaviour each test dictates. That is the point — the
suite proves the engine's contract, not a provider's.
"""
import geopandas as gpd
import pytest
from pyproj import Transformer
from shapely.geometry import box

from app.batch import (
    STATUS_ERROR,
    STATUS_MATCHED,
    STATUS_NO_GEOCODE,
    STATUS_OUTSIDE,
    BatchError,
    ColumnMapping,
)
from app.batch.runner import RateLimiter, run_batch
from app.config import AppConfig, LayerConfig
from app.geocoding.base import GeocodeResult, GeocoderUnavailable
from app.lookup import PolygonLookup

# One square in EPSG:3435 (Illinois State Plane East, ftUS). Query points are
# generated by inverting known planar points back to WGS84, so the test never
# depends on the projection's sign conventions.
CX, CY = 1_100_000.0, 1_900_000.0
HALF = 2_000.0
_INV = Transformer.from_crs("EPSG:3435", "EPSG:4326", always_xy=True)

INSIDE_LON, INSIDE_LAT = _INV.transform(CX, CY)
OUTSIDE_LON, OUTSIDE_LAT = _INV.transform(CX + 50 * HALF, CY)

# A stand-in for a real caseload address. Every PII assertion checks that this
# exact string never reaches a result field it does not belong in.
SECRET_ADDRESS = "1428 N Elm St Apt 3B, Chicago, IL 60622"


@pytest.fixture
def lookup(tmp_path) -> PolygonLookup:
    frame = gpd.GeoDataFrame(
        {"name": ["alpha"], "code": ["A"]},
        geometry=[box(CX - HALF, CY - HALF, CX + HALF, CY + HALF)],
        crs="EPSG:3435",
    )
    gpkg = tmp_path / "squares.gpkg"
    frame.to_file(gpkg, layer="squares", driver="GPKG")
    config = AppConfig(
        layers={
            "squares": LayerConfig(
                id="squares",
                name="Test Squares",
                path=gpkg,
                layer="squares",
                attributes=("name", "code"),
                source="synthetic test fixture",
            )
        }
    )
    return PolygonLookup(config)


class StubGeocoder:
    """A scripted geocoder: hands back queued outcomes, records every query.

    A queued item that is an exception instance is raised instead of returned,
    which is how the "provider dies mid-run" tests are written.
    """

    def __init__(self, outcomes, name="stub"):
        self.name = name
        self._outcomes = list(outcomes)
        self.queries: list[str] = []

    def geocode(self, address: str) -> GeocodeResult:
        self.queries.append(address)
        outcome = self._outcomes.pop(0)
        if isinstance(outcome, Exception):
            raise outcome
        return outcome


def a_hit(query=SECRET_ADDRESS, lon=INSIDE_LON, lat=INSIDE_LAT) -> GeocodeResult:
    return GeocodeResult(
        query=query,
        matched=True,
        provider="stub",
        point=(lon, lat),
        score=95.0,
        matched_address="1428 N ELM ST, CHICAGO, IL, 60622",
    )


ADDRESS_MAPPING = ColumnMapping(address="site_address")
POINT_MAPPING = ColumnMapping(lat="latitude", lon="longitude")


def run(rows, **kwargs):
    return list(run_batch(rows, layer_id="squares", **kwargs))


# ---- the lat/lon path (no geocoder, no network, ever) ----

def test_coordinates_inside_polygon_match(lookup):
    rows = [{"case": "1", "latitude": str(INSIDE_LAT), "longitude": str(INSIDE_LON)}]
    results = run(rows, mapping=POINT_MAPPING, lookup=lookup)

    assert len(results) == 1
    result = results[0]
    assert result.status == STATUS_MATCHED
    assert result.ok is True
    assert result.feature == {"name": "alpha", "code": "A"}
    assert result.lon == pytest.approx(INSIDE_LON)
    assert result.lat == pytest.approx(INSIDE_LAT)
    # Nothing was geocoded, so there is no provider or score to report.
    assert result.provider is None
    assert result.score is None


def test_coordinate_path_never_touches_the_geocoder(lookup):
    # Passing a geocoder that would explode proves the offline path never calls
    # it — this is the "network severed" guarantee, asserted rather than assumed.
    exploding = StubGeocoder([AssertionError("geocoder must not be called")])
    rows = [{"latitude": str(INSIDE_LAT), "longitude": str(INSIDE_LON)}]
    results = run(rows, mapping=POINT_MAPPING, lookup=lookup, geocoder=exploding)

    assert results[0].status == STATUS_MATCHED
    assert exploding.queries == []


def test_coordinate_path_never_uses_the_rate_limiter(lookup):
    limiter = CountingRateLimiter()
    rows = [{"latitude": str(INSIDE_LAT), "longitude": str(INSIDE_LON)}] * 3
    run(rows, mapping=POINT_MAPPING, lookup=lookup, rate_limiter=limiter)
    assert limiter.calls == 0


def test_coordinates_outside_all_polygons(lookup):
    rows = [{"latitude": str(OUTSIDE_LAT), "longitude": str(OUTSIDE_LON)}]
    result = run(rows, mapping=POINT_MAPPING, lookup=lookup)[0]

    assert result.status == STATUS_OUTSIDE
    assert result.ok is False
    assert result.reason == "point_outside_all_polygons"
    assert result.feature is None
    # The point itself is still reported so the operator can see what was tried.
    assert result.lon == pytest.approx(OUTSIDE_LON)


@pytest.mark.parametrize(
    "latitude,longitude",
    [
        ("N/A", "-87.6"),          # a human's "no data" marker
        ("", "-87.6"),             # blank cell
        ("   ", "-87.6"),          # whitespace-only cell
        ("41.88", ""),             # only one of the pair is missing
        ("41,88", "-87.6"),        # European decimal comma
        ("nan", "-87.6"),          # parses as a float but is not a coordinate
    ],
)
def test_unusable_coordinates_are_error_rows(lookup, latitude, longitude):
    rows = [{"latitude": latitude, "longitude": longitude}]
    result = run(rows, mapping=POINT_MAPPING, lookup=lookup)[0]

    assert result.status == STATUS_ERROR
    assert result.reason
    assert result.feature is None


def test_out_of_range_coordinates_are_error_rows(lookup):
    # Latitude 91 is a real number but not a real latitude: the engine raises
    # InvalidCoordinateError, which must degrade to one flagged row.
    rows = [{"latitude": "91.0", "longitude": "-87.6"}]
    result = run(rows, mapping=POINT_MAPPING, lookup=lookup)[0]

    assert result.status == STATUS_ERROR
    assert "WGS84" in result.reason


def test_bad_coordinate_row_does_not_abort_the_run(lookup):
    rows = [
        {"case": "1", "latitude": str(INSIDE_LAT), "longitude": str(INSIDE_LON)},
        {"case": "2", "latitude": "N/A", "longitude": "N/A"},
        {"case": "3", "latitude": str(OUTSIDE_LAT), "longitude": str(OUTSIDE_LON)},
    ]
    results = run(rows, mapping=POINT_MAPPING, lookup=lookup)

    assert [r.status for r in results] == [STATUS_MATCHED, STATUS_ERROR, STATUS_OUTSIDE]
    assert [r.row["case"] for r in results] == ["1", "2", "3"]


# ---- the geocoding path ----

def test_geocoded_row_matches(lookup):
    geocoder = StubGeocoder([a_hit()])
    rows = [{"site_address": SECRET_ADDRESS}]
    result = run(rows, mapping=ADDRESS_MAPPING, lookup=lookup, geocoder=geocoder)[0]

    assert result.status == STATUS_MATCHED
    assert result.feature == {"name": "alpha", "code": "A"}
    assert result.matched_address == "1428 N ELM ST, CHICAGO, IL, 60622"
    assert result.score == 95.0
    assert result.provider == "stub"
    assert geocoder.queries == [SECRET_ADDRESS]


def test_geocoder_no_match_is_no_geocode(lookup):
    geocoder = StubGeocoder([GeocodeResult.no_match(SECRET_ADDRESS, "stub")])
    rows = [{"site_address": SECRET_ADDRESS}]
    result = run(rows, mapping=ADDRESS_MAPPING, lookup=lookup, geocoder=geocoder)[0]

    assert result.status == STATUS_NO_GEOCODE
    assert result.provider == "stub"
    assert result.lon is None and result.lat is None
    assert result.feature is None


def test_geocoded_point_outside_all_polygons(lookup):
    geocoder = StubGeocoder([a_hit(lon=OUTSIDE_LON, lat=OUTSIDE_LAT)])
    rows = [{"site_address": SECRET_ADDRESS}]
    result = run(rows, mapping=ADDRESS_MAPPING, lookup=lookup, geocoder=geocoder)[0]

    assert result.status == STATUS_OUTSIDE
    assert result.reason == "point_outside_all_polygons"
    # A geocoded-but-outside row still carries the geocode, which is exactly the
    # evidence an operator needs to decide whether the layer or the address is
    # at fault.
    assert result.matched_address == "1428 N ELM ST, CHICAGO, IL, 60622"
    assert result.provider == "stub"


def test_blank_address_is_an_error_and_costs_no_request(lookup):
    geocoder = StubGeocoder([a_hit()])
    limiter = CountingRateLimiter()
    rows = [{"site_address": "   "}, {"site_address": SECRET_ADDRESS}]
    results = run(
        rows,
        mapping=ADDRESS_MAPPING,
        lookup=lookup,
        geocoder=geocoder,
        rate_limiter=limiter,
    )

    assert [r.status for r in results] == [STATUS_ERROR, STATUS_MATCHED]
    # The blank row consumed neither a provider request nor a rate-limit slot.
    assert geocoder.queries == [SECRET_ADDRESS]
    assert limiter.calls == 1


def test_geocoder_unavailable_mid_run_does_not_stop_the_run(lookup):
    geocoder = StubGeocoder(
        [
            a_hit(),
            GeocoderUnavailable("connect timeout to https://example.test/geocode"),
            a_hit(),
        ]
    )
    rows = [
        {"case": "1", "site_address": "121 N La Salle St"},
        {"case": "2", "site_address": SECRET_ADDRESS},
        {"case": "3", "site_address": "233 S Wacker Dr"},
    ]
    results = run(rows, mapping=ADDRESS_MAPPING, lookup=lookup, geocoder=geocoder)

    assert [r.status for r in results] == [STATUS_MATCHED, STATUS_ERROR, STATUS_MATCHED]
    assert results[1].reason == "geocoder unavailable"
    # Crucially: rows 3 was still attempted after the failure.
    assert len(geocoder.queries) == 3


def test_unexpected_provider_exception_becomes_one_error_row(lookup):
    # A provider bug (not a GeocoderUnavailable) must not take the run with it.
    geocoder = StubGeocoder([KeyError("candidates"), a_hit()])
    rows = [{"site_address": SECRET_ADDRESS}, {"site_address": "121 N La Salle St"}]
    results = run(rows, mapping=ADDRESS_MAPPING, lookup=lookup, geocoder=geocoder)

    assert [r.status for r in results] == [STATUS_ERROR, STATUS_MATCHED]
    assert "KeyError" in results[0].reason


def test_geocoder_match_without_a_point_is_an_error_row(lookup):
    broken = GeocodeResult(query=SECRET_ADDRESS, matched=True, provider="stub")
    geocoder = StubGeocoder([broken])
    rows = [{"site_address": SECRET_ADDRESS}]
    result = run(rows, mapping=ADDRESS_MAPPING, lookup=lookup, geocoder=geocoder)[0]

    assert result.status == STATUS_ERROR
    assert result.feature is None


# ---- whole-run failures happen before row 1 ----

def test_missing_geocoder_raises_before_any_row_is_processed(lookup):
    # The rows iterator must be untouched: failing on row 1 of 2,000 after a
    # thirty-minute rate-limited wait is the failure mode this guards.
    consumed = []

    def rows():
        for index in range(3):
            consumed.append(index)
            yield {"site_address": SECRET_ADDRESS}

    with pytest.raises(BatchError, match="geocoder"):
        run_batch(
            rows(), mapping=ADDRESS_MAPPING, lookup=lookup, layer_id="squares"
        )

    assert consumed == [], "rows were consumed before the precondition failed"


def test_unknown_layer_raises_before_any_row_is_processed(lookup):
    consumed = []

    def rows():
        consumed.append(1)
        yield {"latitude": str(INSIDE_LAT), "longitude": str(INSIDE_LON)}

    with pytest.raises(BatchError, match="unknown layer"):
        run_batch(
            rows(), mapping=POINT_MAPPING, lookup=lookup, layer_id="no_such_layer"
        )

    assert consumed == []


def test_missing_mapped_column_is_a_whole_run_failure(lookup):
    # A column the file simply does not have is a mapping mistake: stop, rather
    # than emit a file of identical per-row errors.
    rows = [{"lat": str(INSIDE_LAT), "lon": str(INSIDE_LON)}]
    with pytest.raises(BatchError) as raised:
        run(rows, mapping=POINT_MAPPING, lookup=lookup)

    message = str(raised.value)
    # Both the columns that are missing and the ones the source actually has —
    # the same wording sources.validate_column_mapping uses, so one mistake
    # reads the same whichever layer catches it.
    assert "not found" in message
    assert "'latitude'" in message and "'longitude'" in message
    assert "'lat'" in message and "'lon'" in message


# ---- the operator's data survives untouched ----

def test_original_row_is_preserved_verbatim(lookup):
    original = {
        "case": "007",  # leading zero must survive
        "notes": "call before 9am",
        "latitude": str(INSIDE_LAT),
        "longitude": str(INSIDE_LON),
    }
    result = run([dict(original)], mapping=POINT_MAPPING, lookup=lookup)[0]

    assert result.row == original
    assert result.row["case"] == "007"


def test_runner_does_not_mutate_the_input_row(lookup):
    row = {"site_address": SECRET_ADDRESS}
    geocoder = StubGeocoder([a_hit()])
    result = run([row], mapping=ADDRESS_MAPPING, lookup=lookup, geocoder=geocoder)[0]

    assert row == {"site_address": SECRET_ADDRESS}
    assert result.row is row  # returned as-is, not a mangled copy


# ---- SPEC §9: no address ever appears in a reason ----

def test_no_reason_ever_contains_the_queried_address(lookup):
    # Every failure shape the geocoding path can produce, in one run. None of the
    # resulting reason strings may quote the address — a reason is written into
    # the operator's output file and read by whoever they hand it to.
    geocoder = StubGeocoder(
        [
            GeocoderUnavailable(f"HTTP 500 geocoding {SECRET_ADDRESS}"),
            RuntimeError(f"boom while parsing {SECRET_ADDRESS}"),
            GeocodeResult.no_match(SECRET_ADDRESS, "stub"),
            a_hit(lon=OUTSIDE_LON, lat=OUTSIDE_LAT),
        ]
    )
    rows = [{"site_address": SECRET_ADDRESS} for _ in range(4)]
    rows.append({"site_address": ""})  # the blank-address error reason too
    results = run(rows, mapping=ADDRESS_MAPPING, lookup=lookup, geocoder=geocoder)

    assert len(results) == 5
    for result in results:
        reason = result.reason or ""
        assert SECRET_ADDRESS not in reason
        assert "Elm" not in reason
        assert "60622" not in reason


def test_no_reason_contains_the_coordinate_that_failed(lookup):
    # Coordinates are location data too: a rejected lon/lat must not be echoed.
    rows = [{"latitude": "91.123456", "longitude": "-87.987654"}]
    result = run(rows, mapping=POINT_MAPPING, lookup=lookup)[0]

    assert result.status == STATUS_ERROR
    assert "91.123456" not in result.reason
    assert "-87.987654" not in result.reason


# ---- progress callback ----

def test_progress_is_called_once_per_row_with_a_running_count(lookup):
    seen = []
    rows = [
        {"latitude": str(INSIDE_LAT), "longitude": str(INSIDE_LON)},
        {"latitude": "N/A", "longitude": "N/A"},
        {"latitude": str(OUTSIDE_LAT), "longitude": str(OUTSIDE_LON)},
    ]
    def record(rows_done: int, last_status: str) -> None:
        seen.append((rows_done, last_status))

    run(rows, mapping=POINT_MAPPING, lookup=lookup, progress=record)

    assert seen == [
        (1, STATUS_MATCHED),
        (2, STATUS_ERROR),
        (3, STATUS_OUTSIDE),
    ]


def test_results_stream_lazily(lookup):
    # run_batch must yield as it goes, not buffer the whole source: a 50,000-row
    # workbook has to be writable row by row.
    produced = []

    def rows():
        for index in range(3):
            produced.append(index)
            yield {"latitude": str(INSIDE_LAT), "longitude": str(INSIDE_LON)}

    stream = run_batch(
        rows(), mapping=POINT_MAPPING, lookup=lookup, layer_id="squares"
    )
    first = next(stream)
    assert first.status == STATUS_MATCHED
    assert produced == [0], "the whole source was consumed to produce one result"


# ---- rate limiting (with an injected fake clock; no real sleeping) ----

class FakeClock:
    """A monotonic clock the test drives by hand. `sleep` advances it, so the
    limiter's own bookkeeping sees time passing exactly as it would in reality —
    without the test spending a single real second."""

    def __init__(self):
        self.now = 1000.0
        self.sleeps: list[float] = []

    def __call__(self) -> float:
        return self.now

    def sleep(self, seconds: float) -> None:
        self.sleeps.append(seconds)
        self.now += seconds

    def advance(self, seconds: float) -> None:
        self.now += seconds


class CountingRateLimiter:
    """Records `wait()` calls without any timing behaviour."""

    def __init__(self):
        self.calls = 0

    def wait(self) -> None:
        self.calls += 1


def test_rate_limiter_first_call_does_not_wait():
    clock = FakeClock()
    limiter = RateLimiter(1.0, sleep=clock.sleep, clock=clock)
    limiter.wait()
    assert clock.sleeps == []


def test_rate_limiter_sleeps_the_remaining_interval():
    clock = FakeClock()
    limiter = RateLimiter(1.0, sleep=clock.sleep, clock=clock)

    limiter.wait()          # t=1000.0, no wait
    clock.advance(0.25)     # the geocode call took a quarter second
    limiter.wait()          # must sleep the remaining 0.75

    assert clock.sleeps == [pytest.approx(0.75)]
    assert clock.now == pytest.approx(1001.0)


def test_rate_limiter_does_not_sleep_when_the_interval_already_passed():
    clock = FakeClock()
    limiter = RateLimiter(1.0, sleep=clock.sleep, clock=clock)

    limiter.wait()
    clock.advance(5.0)      # a slow provider already ate the budget
    limiter.wait()

    assert clock.sleeps == []


def test_rate_limiter_holds_the_interval_across_many_calls():
    clock = FakeClock()
    limiter = RateLimiter(1.0, sleep=clock.sleep, clock=clock)

    stamps = []
    for _ in range(4):
        limiter.wait()
        stamps.append(clock.now)
        clock.advance(0.1)  # each call takes 0.1s of real work

    gaps = [b - a for a, b in zip(stamps, stamps[1:])]
    assert gaps == [pytest.approx(1.0)] * 3
    assert sum(clock.sleeps) == pytest.approx(2.7)  # 3 x (1.0 - 0.1)


def test_zero_interval_never_sleeps():
    clock = FakeClock()
    limiter = RateLimiter(0, sleep=clock.sleep, clock=clock)
    for _ in range(5):
        limiter.wait()
    assert clock.sleeps == []


def test_negative_interval_is_rejected():
    with pytest.raises(ValueError, match="min_interval_seconds"):
        RateLimiter(-1.0)


def test_run_batch_waits_before_every_geocode_call(lookup):
    clock = FakeClock()
    limiter = RateLimiter(1.0, sleep=clock.sleep, clock=clock)
    geocoder = StubGeocoder([a_hit(), a_hit(), a_hit()])
    rows = [{"site_address": f"{n} Test St"} for n in (1, 2, 3)]

    results = run(
        rows,
        mapping=ADDRESS_MAPPING,
        lookup=lookup,
        geocoder=geocoder,
        rate_limiter=limiter,
    )

    assert [r.status for r in results] == [STATUS_MATCHED] * 3
    # Three geocodes, two enforced gaps of the full interval (the first is free).
    assert clock.sleeps == [pytest.approx(1.0), pytest.approx(1.0)]


def test_rate_limiter_still_applies_to_failing_geocode_calls(lookup):
    # A provider that errors must not become a way to hammer it faster.
    clock = FakeClock()
    limiter = RateLimiter(2.0, sleep=clock.sleep, clock=clock)
    geocoder = StubGeocoder([GeocoderUnavailable("down"), GeocoderUnavailable("down")])
    rows = [{"site_address": "1 Test St"}, {"site_address": "2 Test St"}]

    results = run(
        rows,
        mapping=ADDRESS_MAPPING,
        lookup=lookup,
        geocoder=geocoder,
        rate_limiter=limiter,
    )

    assert [r.status for r in results] == [STATUS_ERROR, STATUS_ERROR]
    assert clock.sleeps == [pytest.approx(2.0)]
