"""F2-T4 — unit tests for the PolygonLookup engine.

Most tests run against a tiny synthetic GeoPackage (two touching squares in
EPSG:3435) so they are fast, deterministic, and independent of the real data.
Query points are generated by inverting known planar (3435) points back to
WGS84 lon/lat, so the test exercises the reprojection in both directions and
does not depend on the sign conventions of the projection. A final test runs
against the shipped data/layers.gpkg.
"""
from pathlib import Path

import geopandas as gpd
import pytest
from pyproj import Transformer
from shapely.geometry import box

from app.config import AppConfig, ConfigError, LayerConfig, load_config
from app.lookup import (
    InvalidCoordinateError,
    PolygonLookup,
    UnknownLayerError,
)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
REAL_CONFIG = PROJECT_ROOT / "config.toml"
REAL_GPKG = PROJECT_ROOT / "data" / "layers.gpkg"

# Two squares in EPSG:3435 (ftUS) near the Illinois State Plane East range, with
# a thin overlap strip straddling x = CX. The overlap (200 ft wide) is what lets
# a point be genuinely covered by BOTH polygons — an exact shared edge can't be
# hit reliably because the WGS84 round-trip perturbs the point by ~1e-4 ft.
CX, CY = 1_100_000.0, 1_900_000.0
HALF = 2_000.0
OVERLAP = 100.0
_INV = Transformer.from_crs("EPSG:3435", "EPSG:4326", always_xy=True)


def _lonlat(x: float, y: float) -> tuple[float, float]:
    """A WGS84 lon/lat that reprojects to planar (x, y) in EPSG:3435."""
    lon, lat = _INV.transform(x, y)
    return lon, lat


@pytest.fixture
def squares_lookup(tmp_path) -> PolygonLookup:
    alpha = box(CX - HALF, CY - HALF, CX + OVERLAP, CY + HALF)  # west, extends east past CX
    beta = box(CX - OVERLAP, CY - HALF, CX + HALF, CY + HALF)  # east, extends west past CX
    frame = gpd.GeoDataFrame(
        {"name": ["alpha", "beta"], "code": ["A", "B"]},
        geometry=[alpha, beta],
        crs="EPSG:3435",
    )
    gpkg = tmp_path / "squares.gpkg"
    frame.to_file(gpkg, layer="squares", driver="GPKG")

    config = AppConfig(
        layers={
            "squares": LayerConfig(
                id="squares",
                name="Test Squares",
                path=gpkg,
                layer="squares",
                attributes=("name", "code"),
                source="synthetic test fixture",
            )
        }
    )
    return PolygonLookup(config)


def test_point_inside_west_square(squares_lookup):
    lon, lat = _lonlat(CX - HALF / 2, CY)  # clearly inside alpha
    match = squares_lookup.locate(lon, lat, "squares")
    assert match.found
    assert match.feature == {"name": "alpha", "code": "A"}


def test_point_inside_east_square(squares_lookup):
    lon, lat = _lonlat(CX + HALF / 2, CY)  # clearly inside beta
    match = squares_lookup.locate(lon, lat, "squares")
    assert match.found
    assert match.feature == {"name": "beta", "code": "B"}


def test_point_in_overlap_is_deterministic(squares_lookup):
    # A point in the overlap strip (x=CX) is covered by BOTH squares; the engine
    # must return a stable, deterministic pick — the first by the first
    # configured attribute ("name").
    lon, lat = _lonlat(CX, CY)
    match = squares_lookup.locate(lon, lat, "squares")
    assert match.found
    assert match.feature["name"] == "alpha"  # sorts before "beta"


def test_point_outside_all_polygons(squares_lookup):
    lon, lat = _lonlat(CX + 10 * HALF, CY)  # far east of both squares
    match = squares_lookup.locate(lon, lat, "squares")
    assert not match.found
    assert match.reason == "point_outside_all_polygons"
    assert match.feature is None


def test_unknown_layer_raises(squares_lookup):
    with pytest.raises(UnknownLayerError):
        squares_lookup.locate(-87.63, 41.88, "no_such_layer")


@pytest.mark.parametrize("lon,lat", [(-999.0, 41.0), (0.0, 91.0), (200.0, 0.0)])
def test_garbage_coordinates_raise(squares_lookup, lon, lat):
    with pytest.raises(InvalidCoordinateError):
        squares_lookup.locate(lon, lat, "squares")


def test_feature_count_and_layer_ids(squares_lookup):
    assert squares_lookup.layer_ids == ("squares",)
    assert squares_lookup.feature_count("squares") == 2


# ---- config loader (F2-T1) ----

def test_load_config_missing_file(tmp_path):
    with pytest.raises(ConfigError):
        load_config(tmp_path / "does_not_exist.toml")


def test_load_config_missing_gpkg(tmp_path):
    bad = tmp_path / "config.toml"
    bad.write_text(
        '[[layers]]\nid="x"\nname="X"\npath="nope.gpkg"\nlayer="x"\n'
        'attributes=["a"]\nsource="s"\n'
    )
    with pytest.raises(ConfigError):
        load_config(bad)


# ---- real shipped data ----

@pytest.mark.skipif(not REAL_GPKG.exists(), reason="data/layers.gpkg not built")
def test_real_data_known_addresses():
    lookup = PolygonLookup(load_config(REAL_CONFIG))

    # Chicago City Hall (121 N LaSalle) → Police District 1 (Central).
    city_hall = lookup.locate(-87.63192, 41.88354, "police_districts")
    assert city_hall.found
    assert city_hall.feature["dist_num"] == "1"

    # Evanston is in Cook County but outside Chicago: no police district, but it
    # IS a municipality — the SPEC §4 "point_outside_all_polygons" case.
    evanston_pd = lookup.locate(-87.68770, 42.04512, "police_districts")
    assert not evanston_pd.found
    assert evanston_pd.reason == "point_outside_all_polygons"

    evanston_muni = lookup.locate(-87.68770, 42.04512, "municipalities")
    assert evanston_muni.found
    assert evanston_muni.feature["muni_name"] == "Evanston"
